### PR TITLE
Fix: Add support for authoring tool 1 (fixes #50)

### LINKED ISSUE #50: Add support for authoring tool 1
As per core issue https://github.com/adaptlearning/adapt_framework/issues/2704

### PR DESCRIPTION
**Pull request by guywillis**
Fixes: #50 

### Fix
* Added new schema files

Dependency: https://github.com/cgkineo/adapt-list/pull/47

### CODE REVIEW

**Comment by joe-replin** [comment]
Note: Unable to test this in https://testing.kineoadapt.com at this time due to not being able to upload new versions of plug-ins. I've added proposed changes from adapt-octopus. Here's a short list.
* Added back your proposed addition of "enum" to "properties" to line 18. I'm not entirely sure what the function of this is.
* Adds descriptions fields throughout
* Adds which fields are translatable
* Added back your proposed title of "Source" on line 136

**Comment by joe-replin** [comment]
Tested in AAT v1. I approve.

**Review by joe-replin — APPROVED** [review]

**Comment by swashbuck** [comment]
Looks like list item graphics aren't showing up in the build (either in the AAT or framework).  I think it's an issue with the JSX.  `_imageSrc` should be `_graphic.src` perhaps?  The AAT settings are fine, but the images are just not displayed.

**Review by swashbuck — APPROVED** [review]
👍

**Pull request merged**
