### PR TITLE
fix example JSON _comment attributes

### PR DESCRIPTION
**Pull request by kirsty-hames**
fixes https://github.com/cgkineo/adapt-list/issues/23

- _comment amended for consistency with other plugins

### CODE REVIEW

**Comment by moloko** [comment]
that's still not valid I'm afraid - now you have duplicate keys!

image

Maybe something like `"_animateList-comment"`?

**Comment by tomgreenfield** [comment]
In this case, [duplicate keys](https://dzone.com/articles/duplicate-keys-in-json-objects) of `_comment` won't break anything in the authoring tool, whereas the current JSON does...

**Comment by tomgreenfield** [comment]
For now, suggest removing all comments apart from the class one. The other attributes are fairly self-explanatory and warrant a trip to the README if clarification is needed.

**Comment by kirsty-hames** [comment]
> For now, suggest removing all comments apart from the class one. The other attributes are fairly self-explanatory and warrant a trip to the README if clarification is needed.

^ amended in last commit @tomgreenfield

**Pull request merged**
