### PR TITLE
Responsive layout amend

### PR DESCRIPTION
**Pull request by guywillis**
Resolves https://github.com/cgkineo/adapt-list/issues/17

* Simplified Less
* Updated comments
* Tied bullet size to icon size

### CODE REVIEW

**Review by kirsty-hames — APPROVED** [review]
Responsive amends look good thanks + 1. 

In regards to the bullet layout, does the 20% width look too big on desktop? 

current_bullet_layout

I see why we set widths for images but do we need to set widths for the bullet layout?

**Comment by guywillis** [comment]
Agreed 20% does look too large, will commit a bullet layout with no width.

**Comment by guywillis** [comment]
Screenshot 2020-09-17 at 17 28 10

**Review by kirsty-hames — APPROVED** [review]
👀

**Pull request merged**
